name: Basic ESMValTool Recipe Execution

on:
  workflow_dispatch:
    inputs:
      recipe:
        description: 'Recipe name to run'
        required: true
        default: 'recipe_example'
      recipe_type:
        description: 'Recipe type'
        required: false
        type: choice
        options:
          - esmvaltool
          - cosima
        default: 'esmvaltool'
      esmvaltool_version:
        description: 'ESMValTool version'
        required: false
        type: choice
        options:
          - main
          - v2.13.0
          - v2.12.0
        default: 'main'

env:
  GADI_USER: ${{ secrets.GADI_USER }}
  GADI_KEY: ${{ secrets.GADI_KEY }}
  GADI_KEY_PASSPHRASE: ${{ secrets.GADI_KEY_PASSPHRASE }}
  SCRIPTS_DIR: ${{ secrets.GADI_SCRIPTS_DIR }}

jobs:
  run-recipe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run Recipe with Smart Recipe Runner
        uses: rbeucher/smart-recipe-runner@main
        with:
          mode: recipe
          recipe_name: ${{ github.event.inputs.recipe }}
          recipe_type: ${{ github.event.inputs.recipe_type }}
          esmvaltool_version: ${{ github.event.inputs.esmvaltool_version }}
